project:
  type: website
  output-dir: docs

website:
  title: "Chris Bowdon"
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/cbowdon
    left:
      - text: Posts
        href: index.qmd
      - text: Rather Old Posts
        menu:
          - text: Medium posts
            href: https://medium.com/@cbowdon
          - text: Working with (around) proxies
            href: proxy.qmd
      - text: "Open Source Software"
        menu:
          - text: "TsMonad"
            href: https://github.com/cbowdon/TsMonad
          - text: daemons.el
            href: https://github.com/cbowdon/daemons.el
      - text: About
        href: about.qmd
  google-analytics: G-QC160P51EN
  open-graph: true
        
format:
  html:
    theme: cosmo
    css: styles.css

