---
title: "How fast Carlos Sainz Jr learns"
date: "2025-03-14"
categories: [f1, r]
---

The MAJOR story of F1's 2025 season is of course the match-up between Sainz and Albon (sorry, did something happen at Ferrari?). Albon's current level is quite a mystery, because since going up against Verstappen as a rookie he has only ever had rookie team mates himself. Sainz on the other hand has been measured against some of the best drivers on the grid and shown himself to be almost on their level.

So far (after two races) Sainz seems to have been on Albon's pace in practice but binned it in Melbourne and struggled with set up in Shanghai. So I got curious about how he did against his previous team mates when he joined the team.

Once again I've made use of data from the excellent Ergast API and processed it with R - unfold for details.

```{r}
#| warning: false
#| label: fig-sainz-advantage
#| fig-cap: Sainz' advantage in seconds over teammates on joining a team (positive advantage means Sainz was faster).
#| code-fold: true
library(tidyverse)
library(forcats)

colours <- tribble(
  ~constructorName, ~colour,
  "Ferrari", "#e80220",
  "McLaren", "#ff8001",
  "Renault", "#ffbb33",
  "Toro Rosso", "#6592ff",
  "williams", "#63c4ff"
)

comparisons <- tribble(
  ~label, ~year, ~from.round, ~driverRef, ~constructorRef,
  "Toro Rosso 2015 (VER)", 2015, 1, "max_verstappen", "toro_rosso",
  "Renault 2017 (HUL)", 2017, 17, "hulkenberg", "renault",
  "Renault 2018 (HUL)", 2018, 1, "hulkenberg", "renault",
  "McLaren 2019 (NOR)", 2019, 1, "norris", "mclaren",
  "Ferrari 2021 (LEC)", 2021, 1, "leclerc", "ferrari"
)

sainz <- comparisons |> mutate(driverRef = "sainz")

drivers <- read_csv("data/drivers.csv", show_col_types = FALSE) |> select(driverId, driverRef, code)
constructors <- read_csv("data/constructors.csv", show_col_types = FALSE) |>
  select(constructorId, constructorRef, name) |>
  rename(constructorName = name)
qualis <- read_csv("data/qualifying.csv", show_col_types = FALSE) |> select(qualifyId, raceId, driverId, constructorId, q1, q2, q3)
races <- read_csv("data/races.csv", show_col_types = FALSE) |>
  select(raceId, year, round, name) |>
  rename(raceName = name)

parse_duration <- function(dur) {
  parts <- strsplit(dur, "[:\\.]")[[1]]
  as.numeric(parts[1]) * 60 + as.numeric(parts[2]) + as.numeric(parts[3]) / 1000
}

df <- bind_rows(
  sainz,
  comparisons
) |>
  merge(drivers) |>
  merge(constructors) |>
  merge(races) |>
  merge(qualis) |>
  filter(round >= from.round & round < from.round + 30) |>
  select(label, code, constructorName, year, round, raceName, q1, q2, q3) |>
  pivot_longer(c(q1, q2, q3), names_to = "qualiSession", values_to = "laptime") |>
  rowwise() |>
  mutate(laptime = if_else(laptime == "\\N", NA, parse_duration(laptime))) |>
  ungroup()

quali.diffs <- df |>
  mutate(driver = if_else(code == "SAI", "Sainz", "Teammate")) |>
  pivot_wider(id_cols = c(label, constructorName, year, round, raceName, qualiSession), names_from = driver, values_from = laptime) |>
  mutate(advantage.sec = Teammate - Sainz, advantage.pc = 100 * (Teammate - Sainz) / Teammate) |>
  filter(!is.na(advantage.sec)) |>
  group_by(year, round) |>
  filter(qualiSession == max(qualiSession)) |>
  arrange(year, round)

ggplot(quali.diffs) +
  aes(x = round, y = advantage.sec, group = constructorName, fill = constructorName) +
  geom_col(colour = "black", linewidth = 0.2) +
  scale_fill_manual(values = colours$colour) +
  facet_wrap(~ fct_reorder(label, year)) +
  scale_y_continuous(limits = c(-1.0, 1.0), oob = scales::squish) +
  labs(
    x = "Number of races",
    y = "Advantage over teammate (s)"
  ) +
  guides(fill = "none") +
  theme_minimal()
```

There's important context here. In Toro Rosso and McLaren, Sainz was teamed with rookies: it was only against Hulkenberg and Leclerc where Sainz stepped into a team with an established driver and had catching up to do. Furthermore, the switch to Renault happened near the end of 2017, so I've included his 2018 season with Renault too.

With that context in mind, it's difficult to draw firm conclusions. It took Sainz about seven races to be competitive with Hulkenberg, if we assume his first round with Renault was a bit lucky. The most relevant experience to his new seat in Williams is against Leclerc in 2021, where it took Sainz three races to qualify ahead and wasn't until the sixth race that he looked to really be on terms with Leclerc. It's not a lot of evidence, but I'll make a prediction anyway: Sainz will gain a consistent advantage over Albon from round six. I'm 90% confident given Albon's performance relative to Colapinto that Sainz will get the upper hand eventually. You can check me on this in a few weeks time!