{
  "hash": "18be4aca54b1a0bff3dd7bb782e288b0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"T. rex size distributions\"\ndate: \"2025-02-15\"\ncategories: [dinosaurs, r]\n---\n\n\n\nI ought to be spending this weekend working on a risk intelligence LLM, but I've stumbled across something that brings my inner child immense joy and such things cannot be ignored. It is this 2019 paper [\"An Older and Exceptionally Large Adult Specimen of Tyrannosaurus rex\"](https://anatomypubs.onlinelibrary.wiley.com/doi/10.1002/ar.24118) by Persons et al. First it's cool to see paleontology in action, instead of filtered through talking head documentaries. Second, the diligent authors have personally measured 12 T. rex specimens, which is a decent chunk of the [29 or-so specimens discovered to-date](https://en.wikipedia.org/wiki/Specimens_of_Tyrannosaurus), and so we have a cool dataset to play with.\n\n\n\n::: {#tbl-dataset .cell tbl-cap='T. rex bone measurements in millimetres (Table 1 from Persons et al 2019).'}\n\n```{.r .cell-code  code-fold=\"true\"}\nlibrary(tidyverse)\nlibrary(knitr)\n\nt.rex <- read_tsv(\"t.rex-persons.tsv\", col_types = \"ccnnnnnnnnnnnnnnn\") |>\n  rename(Specimen = Specimens) |>\n  mutate(Morph = factor(Morph, levels = c(\"Robust\", \"Gracile\")))\n\nkable(t.rex, format.args = list(decimal.mark = \".\", big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|Specimen               |Morph   | Dentary tooth row length| Scapula blade width| Manual p. I-1 length| Ilium length| Femur length| Femur circumference| Proximal femur width| Tibia length| Tibia shaft width| Fibula length| Fibula shaft width| Astragalus height| Astragalus width| Pedal p. IV-1 length| Body mass (kg)|\n|:----------------------|:-------|------------------------:|-------------------:|--------------------:|------------:|------------:|-------------------:|--------------------:|------------:|-----------------:|-------------:|------------------:|-----------------:|----------------:|--------------------:|--------------:|\n|RSM P2523.8            |Robust  |                      595|                74.8|                 98.5|        1,545|        1,333|                 590|                  426|        1,140|               184|           995|                 62|               328|              310|                  184|          8,870|\n|CM 9380 (AMNH 973)     |Robust  |                      508|                73.0|                   NA|        1,540|        1,269|                 534|                  399|        1,166|               150|         1,025|                 NA|                NA|               NA|                  145|          6,740|\n|FMNH PR2081            |Robust  |                      585|                68.0|                 78.0|        1,525|        1,321|                 580|                  380|        1,140|               160|         1,030|                 59|                NA|               NA|                  154|          8,462|\n|MOR 1125               |Robust  |                      492|                65.7|                   NA|           NA|        1,150|                 515|                  370|        1,060|               150|           915|                 53|               280|              295|                  170|          6,100|\n|RTMP 81.12.1, NMC 9950 |Robust  |                       NA|                  NA|                   NA|           NA|           NA|                 495|                   NA|        1,095|               155|           985|                 65|                NA|               NA|                  140|          5,469|\n|BHI 3033               |Gracile |                      575|                  NA|                   NA|        1,540|        1,350|                 505|                  350|        1,065|               158|           945|                 55|               325|              280|                   NA|          5,779|\n|MOR 555                |Gracile |                      635|                65.0|                 89.0|        1,470|        1,280|                 520|                  370|        1,150|               170|         1,035|                 56|                NA|              235|                  176|          6,264|\n|MOR 980                |Gracile |                      546|                  NA|                   NA|        1,397|        1,232|                 483|                   NA|           NA|                NA|            NA|                 NA|                NA|               NA|                   NA|          5,112|\n|RTMP 81.6.1            |Gracile |                      530|                  NA|                   NA|           NA|        1,210|                 460|                  270|        1,030|               160|            NA|                 52|                NA|               NA|                  107|          4,469|\n|BM R8040 (AMNH 5881)   |NA      |                       NA|                  NA|                   NA|           NA|           NA|                 480|                  330|           NA|                NA|            NA|                 NA|                NA|               NA|                  124|          5,025|\n|MOR 009                |NA      |                       NA|                  NA|                 90.0|        1,180|        1,100|                 469|                   NA|        1,105|               140|           930|                 NA|                NA|               NA|                   NA|          4,714|\n|USNM 6183              |NA      |                       NA|                  NA|                   NA|           NA|        1,040|                 426|                   NA|          910|                NA|            NA|                 NA|                NA|               NA|                   NA|          3,617|\n\n\n:::\n:::\n\n\n\nWe can also add \"Goliath\", the exciting 2024 specimen. Bear in mind that Persons didn't personally measure this fossil, so that's a source of potential error. I took the measurements from the few [social media posts](https://www.instagram.com/p/DF-XdPuvXG0/?img_index=1) about the fossil. The lack of information on this specimen seems strange to me, I even wonder if it's a hoax. It wouldn't be the first time.\n\n\n\n::: {#tbl-goliath .cell tbl-cap='Reported measurements for the Goliath specimen.'}\n\n```{.r .cell-code  code-fold=\"true\"}\ncampione.body.mass.kg <- function(min.femoral.circ.mm) 10**((2.754 * log10(min.femoral.circ.mm) - 0.683) - 3)\n\ngoliath <- read_tsv(\"t.rex-goliath.tsv\", col_types = \"ccnnnnnnnnnnnnnnn\") |>\n  mutate(\n    Morph = factor(Morph, levels = c(\"Robust\", \"Gracile\")),\n    `Body mass (kg)` = campione.body.mass.kg(`Femur circumference`)\n  )\n\nt.rex <- bind_rows(t.rex, goliath)\nkable(select(goliath, Specimen, `Femur length`, `Femur circumference`, `Body mass (kg)`))\n```\n\n::: {.cell-output-display}\n\n\n|Specimen | Femur length| Femur circumference| Body mass (kg)|\n|:--------|------------:|-------------------:|--------------:|\n|Goliath  |         1371|                 648|       11483.59|\n\n\n:::\n:::\n\n\n\nThe most interesting bone is the femur, being as it's more likely to be present and is used to estimate body mass. The equation used is from [Campione et al 2014](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.12226). Bear in mind they suggest a 25% prediction error.\n\nAn interesting thing about T. rex is that there are two morphs, _gracile_ and _robust_, which I understand to be layman's terms for \"elven\" and \"chonky\". Let's see if that's visible in the femur measurements.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(t.rex) +\n  aes(x = `Femur length`, y = `Femur circumference`, colour = Morph, label = Specimen) +\n  geom_label(nudge_y = 10, na.rm = TRUE) +\n  geom_point(na.rm = TRUE) +\n  scale_x_continuous(limits = c(1000, 1400)) +\n  scale_y_continuous(limits = c(400, 700)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Femur circumference and length for T. rex specimens.](index_files/figure-html/fig-femurs-1.png){#fig-femurs width=672}\n:::\n:::\n\n\n\nLooking at this scatterplot, there's a linear relationship between length and circumference, and Goliath sits neatly on it. (Too neatly? Hmm. Should it even be linear? Wouldn't the square-cube law suggest femurs should get thicker faster than they get longer?) However it's not obvious if Goliath should be gracile or robust. In fact, it's not particularly clear from the femurs alone why some are gracile and some robust; CM 9380 (Holotype) and MOR 555 (Wankel) are very close, for example. We need more features. Unfortunately, the T. rex data are very sparse, so we need to impute missing values.\n\nTibia length is relatively complete, can we use that?\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(t.rex) +\n  aes(x = `Femur length`, y = `Tibia length`, colour = Morph) +\n  geom_point() +\n  scale_x_continuous(limits = c(1000, 1400)) +\n  scale_y_continuous(limits = c(900, 1200)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Femur length and tibia length for T. rex specimens.](index_files/figure-html/fig-tibias-femur-length-1.png){#fig-tibias-femur-length width=672}\n:::\n:::\n\n\n\nThe relationship between fibia length and tibia length is surprisingly not very informative.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(t.rex) +\n  aes(x = `Femur circumference`, y = `Tibia length`, colour = Morph) +\n  geom_point() +\n  scale_x_continuous(limits = c(400, 700)) +\n  scale_y_continuous(limits = c(900, 1200)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Femur circumference and tibia length for T. rex specimens.](index_files/figure-html/fig-tibias-femur-circumference-1.png){#fig-tibias-femur-circumference width=672}\n:::\n:::\n\n\n\nFemur circumference relates a little better. Let's try a dead simple linear model. We can include body mass, which is a function of femur circumference, to try and capture some of the knowledge from that model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreg <- lm(`Femur length` ~ `Femur circumference` * `Body mass (kg)` + `Tibia length`, data = t.rex, subset = !is.na(t.rex$`Tibia length`) & !is.na(`Femur length`))\nsummary(reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `Femur length` ~ `Femur circumference` * `Body mass (kg)` + \n    `Tibia length`, data = t.rex, subset = !is.na(t.rex$`Tibia length`) & \n    !is.na(`Femur length`))\n\nResiduals:\n       1        2        3        4        6        7        9       11 \n  -2.758   10.381    3.116 -116.353   97.051   30.241   49.109  -69.132 \n      12 \n  -1.655 \n\nCoefficients:\n                                         Estimate Std. Error t value Pr(>|t|)\n(Intercept)                            -1.136e+04  2.430e+04  -0.467    0.665\n`Femur circumference`                   5.020e+01  1.037e+02   0.484    0.654\n`Body mass (kg)`                       -3.832e+00  8.868e+00  -0.432    0.688\n`Tibia length`                         -2.585e-01  8.777e-01  -0.294    0.783\n`Femur circumference`:`Body mass (kg)`  3.317e-03  8.054e-03   0.412    0.702\n\nResidual standard error: 88.3 on 4 degrees of freedom\nMultiple R-squared:  0.6787,\tAdjusted R-squared:  0.3574 \nF-statistic: 2.112 on 4 and 4 DF,  p-value: 0.2433\n```\n\n\n:::\n:::\n\n\n\nIt's not great, though slightly better than the other combinations I tried and probably the best we could do with such a small dataset. The prediction is feasible enough.\n\n\n\n::: {#tbl-with-pred .cell tbl-cap='Imputed femur length for RTMP 81.12.1.'}\n\n```{.r .cell-code  code-fold=\"true\"}\npreds <- predict(reg, newdata = t.rex)\n\nt.rex |>\n  mutate(`Femur length` = coalesce(`Femur length`, preds)) |>\n  select(`Specimen`, `Morph`, `Femur length`, `Femur circumference`, `Tibia length`, `Body mass (kg)`) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Specimen               |Morph   | Femur length| Femur circumference| Tibia length| Body mass (kg)|\n|:----------------------|:-------|------------:|-------------------:|------------:|--------------:|\n|RSM P2523.8            |Robust  |     1333.000|                 590|         1140|        8870.00|\n|CM 9380 (AMNH 973)     |Robust  |     1269.000|                 534|         1166|        6740.00|\n|FMNH PR2081            |Robust  |     1321.000|                 580|         1140|        8462.00|\n|MOR 1125               |Robust  |     1150.000|                 515|         1060|        6100.00|\n|RTMP 81.12.1, NMC 9950 |Robust  |     1230.292|                 495|         1095|        5469.00|\n|BHI 3033               |Gracile |     1350.000|                 505|         1065|        5779.00|\n|MOR 555                |Gracile |     1280.000|                 520|         1150|        6264.00|\n|MOR 980                |Gracile |     1232.000|                 483|           NA|        5112.00|\n|RTMP 81.6.1            |Gracile |     1210.000|                 460|         1030|        4469.00|\n|BM R8040 (AMNH 5881)   |NA      |           NA|                 480|           NA|        5025.00|\n|MOR 009                |NA      |     1100.000|                 469|         1105|        4714.00|\n|USNM 6183              |NA      |     1040.000|                 426|          910|        3617.00|\n|Goliath                |NA      |     1371.000|                 648|           NA|       11483.59|\n\n\n:::\n:::\n\n\n\nI'm not sure what else to do with this.",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}